const data= [
  {
    id:1,
    type:'Waffle',
    name:'Waffle with Berries',
    price: 6.50,
    image:'public/assets/images/image-waffle-desktop.jpg',
    qty: 1,
  },
  {
    id:2,
    type:'Creme Brulee',
    name:'Vanilla Bean Creme Brulee',
    price:7.00,
    image:'public/assets/images/image-creme-brulee-desktop.jpg',
    qty: 1,
  },
  {
    id:3,
    type:'Macaron',
    name: 'Macaron Mix Of Five',
    price:8.00,
    image:'public/assets/images/image-macaron-desktop.jpg',
    qty: 1,
  },
  {
    id:4,
    type:'Tiramisu',
    name:'Classic Tiramisu',
    price:5.50,
    image:'public/assets/images/image-tiramisu-desktop.jpg',
    qty: 1,
  },
  {
    id:5,
    type:'Bakalava',
    name:'Pistachio Bkalava',
    price:4.00,
    image:'public/assets/images/image-baklava-desktop.jpg',
    qty: 1,
  },
  {
    id:6,
    type:'Pie',
    name:'Lemon Meringue Pie',
    price:5.00,
    image:'public/assets/images/image-meringue-desktop.jpg',
    qty: 1,
  },
  {
    id:7,
    type:'Cake',
    name:'Red Velvet Cake',
    price:4.50,
    image:'public/assets/images/image-cake-desktop.jpg',
    qty: 1,
  },
  {
    id:8,
    type:'Browine',
    name:'Salted Caramel Brownie',
    price:5.50,
    image:'public/assets/images/image-brownie-desktop.jpg',
    qty: 1,
  },
  {
    id:9,
    type:'Panna Cotta',
    name:'Vanila Panna Cota',
    price:6.50,
    image:'public/assets/images/image-panna-cotta-desktop.jpg',
    qty: 1,
  },
  
]
export default data;